services:
  api:
    build:
      context: .
      target: final
    ports:
      - 8123:8123
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:alpine
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
